#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config focused_border_color '#75B426'
bspc config window_gap           9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap br &
xsetroot -cursor_name left_ptr &
xrandr --output Virtual1 --mode 1366x768 &
${HOME}/.fehbg &
${HOME}/.config/polybar/iniciar.sh